apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30020
        - containerPort: 30021
---
apiVersion: v1
kind: Service
metadata:
    name: ftps
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
spec:
    type: LoadBalancer
    selector:
      app: ftps
    ports:
      - name: ftps
        port: 21
        protocol: TCP
        targetPort: 21
      - name: passive-min-max
        port: 30021
        protocol: TCP
        targetPort: 30021
